apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: postgresql
    repo: https://charts.bitnami.com/bitnami
    version: 15.5.32
    releaseName: postgres
    namespace: ai-data
    valuesFile: values.yaml
resources:
  - backup-cronjob.yaml
