apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
dependsOn:
  - name: traefik
    namespace: platform-infra
  - name: ingress-nginx
    namespace: platform-infra
resources:
  - helmrepository.yaml
  - helmrelease.yaml
  - cluster-issuer-selfsigned.yaml
