apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: ollama
    repo: https://otwld.github.io/ollama-helm/
    version: '0.63.2'
    releaseName: ollama
    namespace: ai-platform
    valuesFile: values.yaml
resources:
  - scaledobject.yaml
  - servicemonitor.yaml
