apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: minio
    repo: https://charts.bitnami.com/bitnami
    version: 14.8.5
    releaseName: minio
    namespace: ai-data
    valuesFile: values.yaml
