apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sovereign-ai-platform
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/TaheerBinHussain/week-4_AI-Platform.git
    targetRevision: HEAD
    path: argocd/apps/
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
