apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: opentelemetry-collector
  namespace: observability
spec:
  interval: 1h
  url: https://open-telemetry.github.io/opentelemetry-helm-charts
